# serverless.yml

service: ventur-travel-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, 'development'}

functions:
  api:
    handler: src/index.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
# serverless optimization
package:
  individually: true
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
    includeModules: true
    packager: 'npm'
